### ISSUE TITLE
提取的URL判断初步判断

### ISSUE THREAD

**Issue by copybot2022** [F6JO/JsRouteScan#10]
能否对提取的URL格式进行判断，有些场景实际不是URL

GET	/BlsmIWlwrGh1fmGEGIUvY5tIxewNt8DHkeVwLP4CnJk9SIyFrQZDslVDSLZsSJD5QqZhq0kqSbzr7pJRrnbeftkQzaZ/AfUALS44ZAvqAAAAAElFTkSuQmCC

比如判断 目录 长度 正经人谁写30个字母的目录，正经开发不会写大小写随机的目录， 或字符相关性质来判断

**Comment by F6JO** [comment]
过滤的url是可以通过对配置文件添加ExRouteRegexs正则来过滤的，师傅有好的过滤的规则吗，我也更新上

**Comment by winezer0** [comment]
这种不知道用正则怎么写，还有几十像常规的text/html 这种
