### ISSUE TITLE
关于提取js文件中的js文件的问题

### ISSUE THREAD

**Issue by copybot2022** [F6JO/JsRouteScan#11]
好像不会保留js文件中的js文件，需要手动拷贝js文件提取的路径进行访问，才能进一步发现真实的路径

**Comment by F6JO** [comment]
js后缀是过滤的，不会连续的进行访问提取，不过以后这个功能可以考虑添加上

**Comment by winezer0** [comment]
师傅加个vx沟通下开发思路呗，
