### ISSUE TITLE
BUG修复建议，规则优化

### ISSUE THREAD

**Issue by codeyso** [F6JO/JsRouteScan#3]
配置文件中的Regexs，感觉不支持自定义的，我调试了下，用自己匹配接口的正则，会陷入死循环。
正则如下：
(?:"|')(((?:[a-zA-Z]{1,10}://|//)[^"'/]{1,}\.[a-zA-Z]{2,}[^"']{0,})|((?:/|\.\./|\./)[^"'><,;| *()(%%$^/\\\[\]][^"'><,;|()]{1,})|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{1,}\.(?:[a-zA-Z]{1,4}|action)(?:[\?|/][^"|']{0,}|))|([a-zA-Z0-9_\-]{1,}\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml)(?:\?[^"|']{0,}|))|((http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&:/~\+#]*[\w\-\@?^=%&/~\+#])?))(?:"|')

我改成了这种，感觉会好些。
![image](https://github.com/F6JO/JsRouteScan/assets/49984697/3d8f305a-d89d-43d2-931e-a491b81629d3)

**Comment by F6JO** [comment]
新版本已修改，感谢师傅
