### ISSUE TITLE
path

### ISSUE THREAD

**Issue by foyaga** [F6JO/JsRouteScan#5]

**Comment by foyaga** [comment]
path路径怎么变成这样了
![image](https://github.com/F6JO/JsRouteScan/assets/62537001/d97ff14f-828b-49e9-b0f9-70e07d97dffe)

**Comment by F6JO** [comment]
1.2吗师傅，可能是改的有问题，先用1.1吧师傅 我再改改

**Comment by F6JO** [comment]
正则的问题，已经修复了，可以试一下1.2，需要把配置文件手动删除后再加载插件

**Comment by foyaga** [comment]
> 正则的问题，已经修复了，可以试一下1.2，需要把配置文件手动删除后再加载插件

好的，谢谢
